name: CodeQL Analysis

on:
  pull_request:
    branches:
      - release  
  push:
    branches:
      - pipeline  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, This is the Security workflow!"