name: Code Scanning

on:
  pull_request:
    branches:
      - release  
  push:
    branches:
      - dev  

jobs: 

  analyze:        #Job1
    name: Analyze code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:     
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # reference: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
    # Checkout repo  
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }} 
    
    # Build 
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
 
    # Ana;ysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3