name: Main CI/CD Workflow

on:
  push:
    branches:
      - pipeline 
  pull_request:
    branches:
      - pipeline 

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
  ci:
    runs-on: ubuntu-latest

    steps: 
      # Include steps from other workflows
      - name: Run CI Steps
        uses: ./.github/workflows/ci.yaml

  security:
    runs-on: ubuntu-latest

    steps: 

      # Include steps from other workflows
      - name: Run Security Scans
        uses: ./.github/workflows/security.yaml
