name: Create Staging Enviroment

on:
    pull_request:
      branches:
        - release   


jobs:
  create:
    name: 'Create staging enviroment with terraform'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

